In [4]:
import cv2
import random
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

choice = ["Rock", "Paper", "Scissors", "Nothing"]
print (choice[3])

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0] > 0.5:
        print ("Rock")
    elif prediction[0][1] > 0.5:
        print ("Paper")
    elif prediction[0][2] > 0.5:
        print ("Scissors")
    else:
        print ("Nothing")
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

Nothing
Nothing
[[0.07650826 0.00193275 0.1361649  0.7853941 ]]
Nothing
[[0.07055169 0.00152084 0.28641295 0.64151454]]
Nothing
[[0.06595745 0.00126714 0.1393927  0.7933827 ]]
Nothing
[[0.20760442 0.0039078  0.23793173 0.5505561 ]]
Nothing
[[0.04641249 0.00104238 0.06957939 0.88296574]]
Nothing
[[4.2443171e-02 5.2552507e-04 1.7723536e-01 7.7979594e-01]]
Nothing
[[0.06175286 0.0011859  0.20572181 0.7313394 ]]
Nothing
[[0.03936172 0.00110757 0.22641146 0.73311925]]
Nothing
[[0.0908362  0.00184262 0.39440307 0.5129181 ]]
Nothing
[[0.2633622  0.00381045 0.18671298 0.54611444]]
Nothing
[[0.1901116  0.00318139 0.10981767 0.6968894 ]]
Nothing
[[0.29920137 0.00513527 0.26519293 0.4304704 ]]
Nothing
[[0.25057784 0.00923702 0.07306641 0.6671187 ]]
Nothing
[[0.21847516 0.01382231 0.0681937  0.69950885]]
Nothing
[[0.14779967 0.01614434 0.14194776 0.6941082 ]]
Nothing
[[0.20015849 0.00770727 0.10917715 0.6829571 ]]
Nothing
[[0.2900785  0.00639854 0.14153875 0.56198424]]
Nothing
[[0.2952801  0.00682